# Generated by Django 5.1.3 on 2024-11-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='full_name_signer_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='full_name_signer_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(default='Lorem ipsum ...'),
        ),
    ]
